[package]
name = "file_wizard_controllers"
version = "0.1.0"
edition = "2021"

[dependencies]
file_wizard_backend = { path = "../backend" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }