[package]
name = "file_wizard_db"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { workspace = true }
serde = { workspace = true }
log = { workspace = true }

utils = { path = "../utils" }

[lib]
name = "file_wizard_db"
path = "src/lib.rs"
 